version: "3.6"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: laravel-query-builder-powered
    volumes:
      - ".:/var/www/html"
    depends_on:
      - mysql
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'laravel-query-builder-powered'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD: 'laravel'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
      retries: 3
      timeout: 5s
